/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import coffee.machine.Conexao;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;

/**
 *
 * @author aluno
 */
public class Machine extends javax.swing.JFrame {

    /**
     * Creates new form Machine
     */
    public Machine() {
        initComponents();
    }
    
    Conexao conn = new Conexao();
    double total = 0;
    Image img[] = new Image[9];
    Double preco[] = new Double[9];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbfoto2 = new javax.swing.JLabel();
        lbfoto1 = new javax.swing.JLabel();
        lbfoto9 = new javax.swing.JLabel();
        lbfoto6 = new javax.swing.JLabel();
        lbfoto3 = new javax.swing.JLabel();
        lbfoto5 = new javax.swing.JLabel();
        lbfoto4 = new javax.swing.JLabel();
        lbfoto7 = new javax.swing.JLabel();
        lbfoto8 = new javax.swing.JLabel();
        lbvalor9 = new javax.swing.JLabel();
        lbvalor1 = new javax.swing.JLabel();
        lbvalor2 = new javax.swing.JLabel();
        lbvalor3 = new javax.swing.JLabel();
        lbvalor4 = new javax.swing.JLabel();
        lbvalor5 = new javax.swing.JLabel();
        lbvalor6 = new javax.swing.JLabel();
        lbvalor7 = new javax.swing.JLabel();
        lbvalor8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbfoto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbfoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 96, 105));

        lbfoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbfoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 96, 105));

        lbfoto9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbfoto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 96, 105));

        lbfoto6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbfoto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 96, 105));

        lbfoto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbfoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 96, 105));

        lbfoto5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbfoto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 96, 105));

        lbfoto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbfoto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 96, 105));

        lbfoto7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbfoto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 96, 105));

        lbfoto8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbfoto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 96, 105));

        lbvalor9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbvalor9.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbvalor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 80, 20));

        lbvalor1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbvalor1.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbvalor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 20));

        lbvalor2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbvalor2.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbvalor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 80, 20));

        lbvalor3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbvalor3.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbvalor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 80, 20));

        lbvalor4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbvalor4.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbvalor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 20));

        lbvalor5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbvalor5.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbvalor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 80, 20));

        lbvalor6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbvalor6.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbvalor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 80, 20));

        lbvalor7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbvalor7.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbvalor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, 20));

        lbvalor8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbvalor8.setForeground(new java.awt.Color(255, 255, 255));
        lbvalor8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(lbvalor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 80, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("VISOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 120, 40));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 110, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("1");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 70, 60));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("2");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 70, 60));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 70, 60));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("3");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 70, 60));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("5");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 70, 60));

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("6");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 70, 60));

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("7");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 70, 60));

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("8");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 70, 60));

        jButton10.setBackground(new java.awt.Color(51, 51, 51));
        jButton10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("9");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 70, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("TROCO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 70, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Sair");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 80, -1));

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 96, 105));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 100, 110));

        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 270, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        int i = 0;
        try {
            conn.conectar();
            ResultSet rs = conn.buscaCafe();
            while (rs.next()){
                img[i] = Toolkit.getDefaultToolkit().createImage(rs.getBytes("tb01_foto"));
      
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Machine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbfoto1;
    private javax.swing.JLabel lbfoto2;
    private javax.swing.JLabel lbfoto3;
    private javax.swing.JLabel lbfoto4;
    private javax.swing.JLabel lbfoto5;
    private javax.swing.JLabel lbfoto6;
    private javax.swing.JLabel lbfoto7;
    private javax.swing.JLabel lbfoto8;
    private javax.swing.JLabel lbfoto9;
    private javax.swing.JLabel lbvalor1;
    private javax.swing.JLabel lbvalor2;
    private javax.swing.JLabel lbvalor3;
    private javax.swing.JLabel lbvalor4;
    private javax.swing.JLabel lbvalor5;
    private javax.swing.JLabel lbvalor6;
    private javax.swing.JLabel lbvalor7;
    private javax.swing.JLabel lbvalor8;
    private javax.swing.JLabel lbvalor9;
    // End of variables declaration//GEN-END:variables
}
